/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virusscaner;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ThomasBriggs
 */
public class OptionsWindow extends javax.swing.JFrame {

    /**
     * Creates new form Options
     */
    public OptionsWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        virusDBBtn = new javax.swing.JButton();
        usernameBtn = new javax.swing.JButton();
        passwordBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        quarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        virusDBBtn.setText("Virus Database");
        virusDBBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virusDBBtnActionPerformed(evt);
            }
        });

        usernameBtn.setText("Username");
        usernameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameBtnActionPerformed(evt);
            }
        });

        passwordBtn.setText("Password");
        passwordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        quarBtn.setText("Quarantine");
        quarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(closeBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(virusDBBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(virusDBBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void virusDBBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virusDBBtnActionPerformed
        // TODO add your handling code here:
        new VirusDB().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_virusDBBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(User.access < 2){
            virusDBBtn.setEnabled(false);
        }
        if(User.access < 3){
            quarBtn.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void usernameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameBtnActionPerformed
        // TODO add your handling code here:
        Validation val = new Validation();
        if(User.userId.equals("999")){
            JOptionPane.showMessageDialog(null, "This cannot be used with skip at login");
        }else{
            String input = JOptionPane.showInputDialog("Please enter a new username!");
            if(input == null){
                ;
            }else if(val.pCheck(input)==false){
                JOptionPane.showMessageDialog(null, "Please enter username!");
            }else{
                changeUsername(input);
            }
        }
        
    }//GEN-LAST:event_usernameBtnActionPerformed

    private void passwordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordBtnActionPerformed
        // TODO add your handling code here:
        Validation val = new Validation();
        if(User.userId.equals("999")){
            JOptionPane.showMessageDialog(null, "This cannot be used with skip at login");
        }else{
            String input = JOptionPane.showInputDialog("Please enter a password!");
            if(input == null){
                ;
            }else if(val.pCheck(input)==false){
                JOptionPane.showMessageDialog(null, "Please enter a password!");
            }else{
                changePassword(input);
            }
        }
    }//GEN-LAST:event_passwordBtnActionPerformed

    private void quarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarBtnActionPerformed
        // TODO add your handling code here:
        new quarantineDB().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quarBtnActionPerformed

    /**
     *
     * @param newUser
     */
    public void changeUsername(String newUser){
        FileIO io = new FileIO();
        Search se = new Search();
        try {
            String[][] userLogin = io.read2dArray("UserLogin.txt", io.rowAmount("UserLogin.txt"), 3);
            int index = se.idSearch(User.userId, "UserLogin.txt");
            userLogin[index][1] = newUser;
            io.save2dArray("UserLogin.txt", userLogin, io.rowAmount("UserLogin.txt"));
            
        } catch (IOException ex) {
            Logger.getLogger(OptionsWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     *
     * @param newPass
     */
    public void changePassword(String newPass){
        FileIO io = new FileIO();
        Search se = new Search();
        try {
            String[][] userLogin = io.read2dArray("UserLogin.txt", io.rowAmount("UserLogin.txt"), 3);
            int index = se.idSearch(User.userId, "UserLogin.txt");
            userLogin[index][2] = newPass;
            io.save2dArray("UserLogin.txt", userLogin, io.rowAmount("UserLogin.txt"));
            
        } catch (IOException ex) {
            Logger.getLogger(OptionsWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton passwordBtn;
    private javax.swing.JButton quarBtn;
    private javax.swing.JButton usernameBtn;
    private javax.swing.JButton virusDBBtn;
    // End of variables declaration//GEN-END:variables
}
